import re
from pathlib import Path
from django.core.management.base import BaseCommand, CommandError
from django.apps import apps


class Command(BaseCommand):
    """Remove CRUD files generated by suit_model for a given model."""

    def add_arguments(self, parser):
        parser.add_argument('model_name', type=str)
        parser.add_argument('app', type=str)

    def _has_syntax_error(self, filepath):
        """Check if a Python file has syntax errors by trying to compile it."""
        try:
            compile(filepath.read_text(), filepath.name, 'exec')
            return False
        except SyntaxError:
            return True

    def _remove_orphaned_imports(self, text, model_name):
        """Remove orphaned import lines that import the given model_name but aren't followed by its usage."""
        lines = text.splitlines(keepends=True)
        new_lines = []
        skip_next = False
        for i, line in enumerate(lines):
            stripped = line.strip()
            # Check if this is a standalone import like `from .models import ModelName`
            # that isn't part of a multi-import line
            if stripped.startswith('from ') and 'import ' in stripped:
                imports_part = stripped.split('import ', 1)[1].strip()
                # Split on commas to handle "from .models import A, B, C"
                imported_names = [x.strip() for x in imports_part.split(',')]
                if model_name in imported_names:
                    # Check if this import is actually used in the remaining lines
                    # (skip self-referential check)
                    remaining = ''.join(lines[i+1:])
                    if model_name not in remaining:
                        continue  # drop this line
            new_lines.append(line)

        # Also handle duplicate consecutive import blocks for the same model
        result = ''.join(new_lines)
        # Remove duplicate standalone import+class blocks that may have been left
        # For example repeated: "from django.contrib import admin\nfrom .models import X\n\n@admin.register(X)\nclass XAdmin..."
        # We do a more aggressive pass: remove any block where the import and class refer to the same model
        result = re.sub(
            rf'(from django\.contrib import admin\nfrom \.models import {re.escape(model_name)}\n\n'
            rf'@admin\.register\({re.escape(model_name)}\)\n'
            rf'class {re.escape(model_name)}Admin\(.*?\):\n'
            rf'(?:[ \t]+.*\n?)*\n?)'
            r'\s*\1',  # remove if duplicated immediately
            r'\1',
            result,
            flags=re.DOTALL
        )
        return result

    def _remove_import_lines(self, text, model_name):
        """Remove all standalone import lines that import model_name, even if used elsewhere.
        Only safe to call AFTER the class has been removed."""
        lines = text.splitlines(keepends=True)
        new_lines = []
        for line in lines:
            stripped = line.strip()
            # Match: `from .models import ModelName` and `from .models import ModelName, Other`
            if stripped.startswith('from ') and 'import ' in stripped:
                imports_part = stripped.split('import ', 1)[1].strip()
                imported_names = [x.strip() for x in imports_part.split(',')]
                if model_name in imported_names:
                    continue
            new_lines.append(line)
        return ''.join(new_lines)

    def _remove_class_from_file(self, filepath, class_name, model_name=None):
        """Remove a class definition (and its decorator) from a Python file.
        Also cleans up orphaned import lines for model_name after removal."""
        if not filepath.exists():
            return False

        # First, if the file has syntax errors, log a warning and try to repair
        if self._has_syntax_error(filepath):
            self.stdout.write(self.style.WARNING(
                f"  File {filepath} has syntax errors; attempting to repair before removal."))
            text = filepath.read_text()
            # Repair strategy: remove any line that has the concatenation pattern
            # (e.g. `fields.DateTimeField()from django import forms`)
            text = re.sub(r'\)(from\s+[\w.]+)', r')\n\1', text)
            # Remove incomplete decorator+class blocks where class body is missing
            # Also try with model_name as register() argument (admin.py uses model name, not class name)
            register_text = text
            for arg in [class_name, model_name] if model_name and model_name != class_name else [class_name]:
                candidate = re.sub(
                    rf'@\w+\.register\({re.escape(arg)}\)\s*\n'
                    rf'(?!class\s+)',
                    '',
                    register_text
                )
                if candidate != register_text:
                    register_text = candidate
                    break
            text = register_text
            filepath.write_text(text)
            if self._has_syntax_error(filepath):
                self.stdout.write(self.style.ERROR(
                    f"  Could not repair syntax errors in {filepath}; skipping."))
                return False

        text = filepath.read_text()
        original_text = text

        # Remove decorator line + class + body (indented lines) until next top-level construct
        # Try matching with class_name first, then model_name (admin.py uses model name in register())
        new_text = text
        count = 0
        for arg in [class_name, model_name] if model_name and model_name != class_name else [class_name]:
            decorator_class_pattern = re.compile(
                rf'@\w+\.register\({re.escape(arg)}\)\s*\n'
                rf'class {re.escape(class_name)}\(.*?\):\n'
                rf'(?:[ \t]+.*\n?)*',
                re.MULTILINE | re.DOTALL
            )
            new_text, count = decorator_class_pattern.subn('', text, count=1)
            if count > 0:
                break

        if count == 0:
            # Try without decorator
            class_pattern = re.compile(
                rf'class {re.escape(class_name)}\(.*?\):\n'
                rf'(?:[ \t]+.*\n?)*',
                re.MULTILINE | re.DOTALL
            )
            new_text, count = class_pattern.subn('', text, count=1)

        if count > 0:
            # Remove orphaned import lines for this model
            if model_name:
                new_text = self._remove_import_lines(new_text, model_name)

            # Also try to remove duplicate/redundant import blocks
            new_text = self._remove_orphaned_imports(new_text, model_name or class_name.replace(
                'Admin', '').replace('Form', '').replace('Factory', '').replace('Serializer', ''))

            # Clean up blank lines
            new_text = re.sub(r'\n{3,}', '\n\n', new_text)
            new_text = new_text.strip()
            if new_text:
                new_text += '\n'
            filepath.write_text(new_text)
            return True

        # Second pass: if text wasn't modified but contains orphaned import lines, clean them
        if model_name:
            cleaned = self._remove_import_lines(original_text, model_name)
            if cleaned != original_text:
                cleaned = re.sub(r'\n{3,}', '\n\n', cleaned)
                cleaned = cleaned.strip()
                if cleaned:
                    cleaned += '\n'
                filepath.write_text(cleaned)
                return True

        return False

    def _remove_from_urls(self, filepath, snake_name):
        """Remove URL patterns for a given snake_name from urls.py."""
        if not filepath.exists():
            return False
        text = filepath.read_text()
        # Remove the two path lines for this model
        lines = text.splitlines(keepends=True)
        new_lines = []
        removed = False
        for line in lines:
            stripped = line.strip()
            if (stripped.startswith(f"path('{snake_name}/'") or
                    stripped.startswith(f"path('{snake_name}/<int:pk>/'")):
                removed = True
                continue
            new_lines.append(line)
        if removed:
            new_text = ''.join(new_lines)
            # Remove empty urlpatterns += [ ] blocks left behind
            new_text = re.sub(
                r'urlpatterns\s*\+=\s*\[\s*\]\s*\n?',
                '',
                new_text
            )
            # Remove orphaned standalone app_name lines (may be left after empty block removal)
            new_text = re.sub(
                r'^app_name\s*=\s*[\'\"][\w]+[\'\"]\s*\n',
                '',
                new_text,
                flags=re.MULTILINE
            )
            new_text = re.sub(r'\n{3,}', '\n\n', new_text)
            new_text = new_text.strip()
            if new_text:
                new_text += '\n'
            filepath.write_text(new_text)
        return removed

    def _remove_from_sidebar(self, model_name):
        """Remove the sidebar entry for the model."""
        project_root = Path(__file__).resolve(
        ).parent.parent.parent.parent.parent
        sidebar_path = project_root / "templates" / \
            "cotton" / "fancy" / "sidebar" / "sidebar.html"
        if not sidebar_path.exists():
            self.stdout.write(self.style.WARNING(
                f"Could not find {sidebar_path}; skipping sidebar removal."))
            return False
        text = sidebar_path.read_text()
        # Match the entire <c-fancy.sidebar.piece name="ModelName" ...> block
        pattern = re.compile(
            rf'            <c-fancy\.sidebar\.piece name="{model_name}".*?</c-fancy\.sidebar\.piece>\n',
            re.DOTALL
        )
        new_text, count = pattern.subn('', text, count=1)
        if count == 0:
            self.stdout.write(self.style.WARNING(
                f"Sidebar entry for '{model_name}' not found."))
            return False
        new_text = re.sub(r'\n{3,}', '\n\n', new_text)
        sidebar_path.write_text(new_text)
        self.stdout.write(self.style.SUCCESS(
            f"Removed '{model_name}' from sidebar."))
        return True

    def _remove_view_file(self, app_path, snake_name, model_name):
        """Remove view file and clean up views/__init__.py."""
        views_dir = app_path / "views"
        view_file = views_dir / f"{snake_name}.py"

        if view_file.exists():
            view_file.unlink()
            self.stdout.write(self.style.SUCCESS(
                f"Deleted view at {view_file}"))

            # Clean up views/__init__.py
            init_file = views_dir / "__init__.py"
            if init_file.exists():
                text = init_file.read_text()
                import_line = f"from .{snake_name} import {model_name}View\n"
                all_entry = f"    '{model_name}View',\n"
                new_text = text.replace(import_line, '')
                new_text = new_text.replace(all_entry, '')
                new_text = re.sub(r'\n{3,}', '\n\n', new_text)
                new_text = new_text.strip()
                if new_text:
                    new_text += '\n'
                init_file.write_text(new_text)
                self.stdout.write(self.style.SUCCESS(
                    f"Cleaned {model_name}View from views/__init__.py"))
            return True

        # Legacy mode: view is in views.py
        views_py = app_path / "views.py"
        if views_py.exists():
            return self._remove_class_from_file(views_py, f"{model_name}View")

        self.stdout.write(self.style.WARNING(
            f"No view file found for {model_name}."))
        return False

    def _remove_template(self, app_path, app_label, snake_name):
        """Delete the template file."""
        tpl_file = app_path / "templates" / app_label / f"{snake_name}.html"
        if tpl_file.exists():
            tpl_file.unlink()
            self.stdout.write(self.style.SUCCESS(
                f"Deleted template at {tpl_file}"))
            return True
        self.stdout.write(self.style.WARNING(
            f"Template {tpl_file} not found."))
        return False

    def _remove_test_file(self, app_path, snake_name):
        """Delete the test file."""
        test_file = app_path / "tests" / "test_views" / f"test_{snake_name}.py"
        if test_file.exists():
            test_file.unlink()
            self.stdout.write(self.style.SUCCESS(
                f"Deleted test at {test_file}"))
            return True
        self.stdout.write(self.style.WARNING(
            f"Test {test_file} not found."))
        return False

    def handle(self, *args, **options):
        model_name = options['model_name']
        if not model_name[0].isupper():
            raise CommandError(
                f"Model name '{model_name}' must start with an uppercase letter (e.g., '{model_name.capitalize()}')."
            )
        app_label = options['app']
        snake_name = model_name.lower()

        try:
            app_path = Path(apps.get_app_config(app_label).path)
        except LookupError:
            self.stdout.write(self.style.ERROR(
                f"App '{app_label}' not found."))
            return

        self.stdout.write(self.style.NOTICE(
            f"Unsuiting {app_label}.{model_name}..."))

        # 1. Remove form class
        forms_py = app_path / "forms.py"
        if self._remove_class_from_file(forms_py, f"{model_name}Form", model_name=model_name):
            self.stdout.write(self.style.SUCCESS("  ✓ Removed form class"))
        else:
            self.stdout.write(self.style.WARNING("  - Form class not found"))

        # 2. Remove serializer class
        serializers_py = app_path / "serializers.py"
        if self._remove_class_from_file(serializers_py, f"{model_name}Serializer", model_name=model_name):
            self.stdout.write(self.style.SUCCESS(
                "  ✓ Removed serializer class"))
        else:
            self.stdout.write(self.style.WARNING(
                "  - Serializer class not found"))

        # 3. Remove admin registration
        admin_py = app_path / "admin.py"
        if self._remove_class_from_file(admin_py, f"{model_name}Admin", model_name=model_name):
            self.stdout.write(self.style.SUCCESS(
                "  ✓ Removed admin registration"))
        else:
            self.stdout.write(self.style.WARNING(
                "  - Admin registration not found"))

        # 4. Remove view file
        self._remove_view_file(app_path, snake_name, model_name)

        # 5. Remove template
        self._remove_template(app_path, app_label, snake_name)

        # 6. Remove URL patterns
        urls_py = app_path / "urls.py"
        if self._remove_from_urls(urls_py, snake_name):
            self.stdout.write(self.style.SUCCESS("  ✓ Removed URL patterns"))
        else:
            self.stdout.write(self.style.WARNING("  - URL patterns not found"))

        # 7. Remove from sidebar
        self._remove_from_sidebar(model_name)

        # 8. Remove factory class
        factories_py = app_path / "factories.py"
        if self._remove_class_from_file(factories_py, f"{model_name}Factory", model_name=model_name):
            self.stdout.write(self.style.SUCCESS("  ✓ Removed factory class"))
        else:
            self.stdout.write(self.style.WARNING(
                "  - Factory class not found"))

        # 9. Remove test file
        self._remove_test_file(app_path, snake_name)

        self.stdout.write(self.style.SUCCESS(
            f"\nDone unsuiting {app_label}.{model_name}."))