apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    uid: "ff0lt29e1hrswa"
    access: proxy
    isDefault: true
    jsonData:
      httpMethod: POST
