server {
    listen 443 ssl;

    server_name {{cookiecutter.domain_name}};

    ssl_certificate /etc/letsencrypt/live/{{cookiecutter.domain_name}}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{{cookiecutter.domain_name}}/privkey.pem;

    location / {
        proxy_pass http://django:8000;
    }

    location /static/ {
        alias /static/;
    }
}

server {
    listen 443 ssl;

    server_name jenkins.{{cookiecutter.domain_name}};

    ssl_certificate /etc/letsencrypt/live/{{cookiecutter.domain_name}}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{{cookiecutter.domain_name}}/privkey.pem;

    location / {
        proxy_pass http://{{cookiecutter.__project_slug}}-jenkins-container:8080;
    }
}


server {
    listen 443 ssl;

    server_name prometheus.{{cookiecutter.domain_name}};

    ssl_certificate /etc/letsencrypt/live/{{cookiecutter.domain_name}}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{{cookiecutter.domain_name}}/privkey.pem;

    return 200 'prometheus.{{cookiecutter.domain_name}} certificate successfully installed!';
    add_header Content-Type text/plain;
}


server {
    listen 443 ssl;

    server_name grafana.{{cookiecutter.domain_name}};

    ssl_certificate /etc/letsencrypt/live/{{cookiecutter.domain_name}}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{{cookiecutter.domain_name}}/privkey.pem;

    return 200 'grafana.{{cookiecutter.domain_name}} certificate successfully installed!';
    add_header Content-Type text/plain;
}


server {
    listen 8080;

    location /stub_status {
        stub_status;
        allow 127.0.0.1;
        deny all;
    }
}