server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://django:8000;
    }

    location /static/ {
        alias /static/;
    }
}

server {
    listen 80;
    server_name jenkins.localhost;

    location / {
        proxy_pass http://jenkins:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;

        proxy_redirect http://jenkins:8080 http://jenkins.localhost;
    }
}

server {
    listen 80;
    server_name prometheus.localhost;

    location / {
        proxy_pass http://prometheus:9090;
    }
}

server {
    listen 80;
    server_name grafana.localhost;

    location / {
        proxy_set_header Host $http_host;
        proxy_pass http://grafana:3000;
    }
}

server {
    listen 8080;
    server_name localhost;

    location /stub_status {
        stub_status;
        allow 172.16.0.0/12; 
        allow 127.0.0.1;
        deny all;
    }
}